package model;



import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Incidencia generated by hbm2java
 */
@Entity
@Table(name="incidencia"
    ,catalog="hdsoft_bd"
)
public class Incidencia  implements java.io.Serializable {


     private Integer id;
     private Activos activos;
     private Usuario usuario;
     private int tipo;
     private String nombre;
     private int prioridad;
     private int estado;
     private Date fechaInicio;
     private Date fechaFin;
     private Set actividads = new HashSet(0);

    public Incidencia() {
    }

	
    public Incidencia(Usuario usuario, int tipo, String nombre, int prioridad, int estado, Date fechaInicio) {
        this.usuario = usuario;
        this.tipo = tipo;
        this.nombre = nombre;
        this.prioridad = prioridad;
        this.estado = estado;
        this.fechaInicio = fechaInicio;
    }
    public Incidencia(Activos activos, Usuario usuario, int tipo, String nombre, int prioridad, int estado, Date fechaInicio, Date fechaFin, Set actividads) {
       this.activos = activos;
       this.usuario = usuario;
       this.tipo = tipo;
       this.nombre = nombre;
       this.prioridad = prioridad;
       this.estado = estado;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.actividads = actividads;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="activo")
    public Activos getActivos() {
        return this.activos;
    }
    
    public void setActivos(Activos activos) {
        this.activos = activos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="tipo", nullable=false)
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="nombre", nullable=false, length=250)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="prioridad", nullable=false)
    public int getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(int prioridad) {
        this.prioridad = prioridad;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    @Column(name="fecha", nullable=false, length=250)
    public String getFecha() {
        Date now=new Date();
        SimpleDateFormat sm = new SimpleDateFormat("yyyy-MM-dd");        
        String fec = sm.format(now);
        return fec;
    }
    
    

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="incidencia")
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }

    @Override
    public String toString() {
        return nombre;
    }




}


